### ISSUE TITLE
aria-hidden="true" for dashicons

### ISSUE THREAD

**Issue by samikeijonen** [justintadlock/butterbean#1]
I'd probably add `aria-hidden="true"` to dashicons: `<i class="dashicons dashicons-edit" aria-hidden="true"></i>`. That prevent them to be read by screen readers.

**Comment by justintadlock** [comment]
Fixed: https://github.com/justintadlock/butterbean/commit/e27ad6d74b193a4eba94e4c11ddace988f62011e
