### ISSUE TITLE
Maybe combine register_control and register_setting?

### ISSUE THREAD

**Issue by timiwahalahti** [justintadlock/butterbean#10]
Is there any reason why `register_control` could not call `register_setting` internally? It feels little annoying that i need to call both functions for registering one field, when it would be possible to just add `sanitize_callback` argument to `register_control` function.

In my opinion, calling `register_setting` makes code tangled and unnecessarily long especially when there is many fields.

**Comment by justintadlock** [comment]
How do you propose handling controls with multiple settings?

**Comment by justintadlock** [comment]
I'm not against the idea of a built-in wrapper function for single-control + single-setting groups.

**Comment by justintadlock** [comment]
Something like:

```
$manager->register_field(
    $name,
    $control_args, // Calls `register_control()` internally.
    $setting_args  // Calls `register_setting()` internally.
);
```

That'd probably work when a control is only tied to a single setting.  It's something I've thought about, but I want to get the base functionality down first.

**Comment by timiwahalahti** [comment]
I see that you added this wrapper function in latest [commit](https://github.com/justintadlock/butterbean/commit/525b21dc39a2d802f2c41a978db8aa23375a7556), thanks!
