### ISSUE TITLE
Term metadata

### ISSUE THREAD

**Issue by rogercoathup** [justintadlock/butterbean#21]
@justintadlock -- any plans to extend Butterbean to support taxonomy term meta boxes?

**Comment by justintadlock** [comment]
No.  It's a post meta box framework.

We'll talk if/when core WP allows meta boxes on the edit term screen.

**Comment by caercam** [comment]
Makes sense.

Meanwhile, to anyone who may be interested in using Term Meta, meet [Haricot](https://github.com/CaerCam/Haricot), a simple ButterBean clone for taxonomies. [Example plugin](https://github.com/CaerCam/Haricot-Example) available too.
