### ISSUE TITLE
WordPress PHP Coding Standards

### ISSUE THREAD

**Issue by slaFFik** [justintadlock/butterbean#25]
Could you please follow WordPress PHP Coding Standards?

I'm partucularly asking about braces: 
https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#brace-style

Example:

``` php
// If we have don't have a new value but do have an old one, delete it.
if ( ! $new_value && $old_value )
    delete_post_meta( $this->manager->post_id, $this->name );

// If the new value doesn't match the old value, set it.
else if ( $new_value !== $old_value )
    update_post_meta( $this->manager->post_id, $this->name, $new_value );
```

Adding `{}` will greatly improve readability.

**Comment by justintadlock** [comment]
No.

See: https://github.com/justintadlock/butterbean/blob/master/contributing.md#coding-standards
