### ISSUE TITLE
Control `image` bug & improvement

### ISSUE THREAD

**Issue by slaFFik** [justintadlock/butterbean#26]
Currently if you register CPT without "content" and featured image sections in `supports` array - `image` control won't work (will through a js error in console).

Reason: `wp_enqueue_media()` didn't run (because it is tightened to `wp_editor` which is absent in this scenario) and appropriate js libraries are not loaded.

Proposing: when registering `image` control also run `wp_enqueue_media()` to the enqueue queue.

**Comment by justintadlock** [comment]
Yep, I knew about this weeks ago.  I thought we had a ticket for it.

**Comment by m-e-h** [comment]
https://themehybrid.slack.com/archives/general/p1470253877000057

From that conversation:

> Can you test out changing this line in `inc/controls/class-control-image.php`:
> `wp_enqueue_script( 'media-views' );`
> with this line:
> `wp_enqueue_media();`

Worked for me.

**Comment by justintadlock** [comment]
@m-e-h That's why we need tickets.  I tend to forget things. :)

**Comment by justintadlock** [comment]
This should be fixed now.
