### ISSUE TITLE
Multiple images control

### ISSUE THREAD

**Issue by nicolas92** [justintadlock/butterbean#40]
Hello, I love your plugin, I can do what I want except for an option, I would like to create a gallery, but there is no control for it.
Is it possible to create one?
I think several users would like this control.
Thank you very much and happy new year :)

**Comment by m-e-h** [comment]
Hey @nicolas92 
There has been some discussion about a gallery type control in https://github.com/justintadlock/butterbean/issues/3

**Comment by justintadlock** [comment]
Yep, I'm going to close this one so that discussion stays over in #3.  This is definitely one of the controls at the top of my list to add.

**Comment by nicolas92** [comment]
Hi, okay, thank you very much :)
